services:
  - type: web
    name: improve-product-statistics-bot
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 